### ISSUE TITLE
Module is not redirecting to CAS server URL

### ISSUE THREAD

**Issue by scottmetoyer** [biblibre/omeka-s-module-CAS#1]
The module appears to be appending my CAS server URL to my Omeka domain name instead of redirecting to the CAS server.

My Omeka instance is hosted at omeka.ucr.edu/collections. My CAS server URL is auth.ucr.edu. I have 'https://auth.ucr.edu' set as the CAS server URL in the module configuration.

When I click 'Log in using CAS' this is the URL that appears in the address bar:

https://omeka.ucr.edu/collections/cas/%20https://auth.ucr.edu/login?service=https%3A%2F%2Fomeka.ucr.edu%2Fcollections%2Fcas%2Fvalidate 

It should be :

https://auth.ucr.edu/login?service=https%3A%2F%2Fomeka.ucr.edu%2Fcollections%2Fcas%2Fvalidate 

Any idea what's going on?

**Comment by jajm** [comment]
> https://omeka.ucr.edu/collections/cas/%20https://auth.ucr.edu/login?service=https%3A%2F%2Fomeka.ucr.edu%2Fcollections%2Fcas%2Fvalidate

The `%20` you have before your CAS server url is a space. I guess that you entered a leading space in the module configuration and your browser think it's a relative url.
I'll see if I can do something about it, but you should be able to fix it by removing that space

**Comment by jajm** [comment]
This is fixed in release 0.4.2

https://github.com/biblibre/omeka-s-module-CAS/releases/tag/v0.4.2

**Comment by scottmetoyer** [comment]
That was exactly it - my mistake. Thanks!
